<a href="https://colab.research.google.com/github/mgodfrey1294/Pandas-Tutorial-Youtube/blob/main/Add_Column.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
# import csv file
my_df = pd.read_csv('https://raw.githubusercontent.com/flatplanet/Pandas-Youtube-Playlist/main/dog_data.csv')
my_df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [19]:
# Add Column From List
my_df2 = my_df.iloc[:5,]
my_df2
gender = ["Male", "Female", "Male", "Male", "Female"]
my_df2["Gender"] = gender
my_df2

<ipython-input-19-a14368b4ac16>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_df2["Gender"] = gender

                 Breed        Color  DogName  OwnerZip  Gender
0             COCKAPOO        BROWN  CHARLEY     15236    Male
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238  Female
2        BELG MALINOIS      BRINDLE     EICH     15238    Male
3                MIXED  BLACK/BROWN    ARROW     15104    Male
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139  Female

In [20]:
# Add Default Values
my_df["Alive/Dead"] = [True]*len(my_df)
my_df

,Breed,Color,DogName,OwnerZip,Alive/Dead
0,COCKAPOO,BROWN,CHARLEY,15236,True
1,GER SHEPHERD,BLACK/BROWN,TACODA,15238,True
2,BELG MALINOIS,BRINDLE,EICH,15238,True
3,MIXED,BLACK/BROWN,ARROW,15104,True
4,AM PIT BULL TERRIER,WHITE/BROWN,OAKLEY,15139,True
...,...,...,...,...,...
2665,GOLDENDOODLE,BROWN,WINSLOW,15044,True
2666,YORKSHIRE TERRIER,BLACK/BROWN,ROCKY KALAKOS,15220,True
2667,LAB MIX,WHITE/BLACK/BROWN,ELLIE,15220,True
2668,GOLDENDOODLE,WHITE,CLARENCE,15143,True
2669,SHETLAND SHEEPDOG,BLACK,GRIFFIN,15136,True

In [22]:
# Add NaN Value
my_df["Show Dog"] = [np.nan]*len(my_df)
my_df

,Breed,Color,DogName,OwnerZip,Alive/Dead,Show Dog
0,COCKAPOO,BROWN,CHARLEY,15236,True,NaN
1,GER SHEPHERD,BLACK/BROWN,TACODA,15238,True,NaN
2,BELG MALINOIS,BRINDLE,EICH,15238,True,NaN
3,MIXED,BLACK/BROWN,ARROW,15104,True,NaN
4,AM PIT BULL TERRIER,WHITE/BROWN,OAKLEY,15139,True,NaN
...,...,...,...,...,...,...
2665,GOLDENDOODLE,BROWN,WINSLOW,15044,True,NaN
2666,YORKSHIRE TERRIER,BLACK/BROWN,ROCKY KALAKOS,15220,True,NaN
2667,LAB MIX,WHITE/BLACK/BROWN,ELLIE,15220,True,NaN
2668,GOLDENDOODLE,WHITE,CLARENCE,15143,True,NaN
2669,SHETLAND SHEEPDOG,BLACK,GRIFFIN,15136,True,NaN

In [25]:
# Add column with .insert() - Allows Position
my_df.insert(1, "Adopted", [True]*len(my_df), True)
my_df

,Breed,Adopted,Color,DogName,OwnerZip,Alive/Dead,Show Dog
0,COCKAPOO,True,BROWN,CHARLEY,15236,True,NaN
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,True,NaN
2,BELG MALINOIS,True,BRINDLE,EICH,15238,True,NaN
3,MIXED,True,BLACK/BROWN,ARROW,15104,True,NaN
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,True,NaN
...,...,...,...,...,...,...,...
2665,GOLDENDOODLE,True,BROWN,WINSLOW,15044,True,NaN
2666,YORKSHIRE TERRIER,True,BLACK/BROWN,ROCKY KALAKOS,15220,True,NaN
2667,LAB MIX,True,WHITE/BLACK/BROWN,ELLIE,15220,True,NaN
2668,GOLDENDOODLE,True,WHITE,CLARENCE,15143,True,NaN
2669,SHETLAND SHEEPDOG,True,BLACK,GRIFFIN,15136,True,NaN

In [26]:
# Add column with .assign() - Creates new df
my_df2 = my_df.assign(Horse=[False]*len(my_df))
my_df2

,Breed,Adopted,Color,DogName,OwnerZip,Alive/Dead,Show Dog,Horse
0,COCKAPOO,True,BROWN,CHARLEY,15236,True,NaN,False
1,GER SHEPHERD,True,BLACK/BROWN,TACODA,15238,True,NaN,False
2,BELG MALINOIS,True,BRINDLE,EICH,15238,True,NaN,False
3,MIXED,True,BLACK/BROWN,ARROW,15104,True,NaN,False
4,AM PIT BULL TERRIER,True,WHITE/BROWN,OAKLEY,15139,True,NaN,False
...,...,...,...,...,...,...,...,...
2665,GOLDENDOODLE,True,BROWN,WINSLOW,15044,True,NaN,False
2666,YORKSHIRE TERRIER,True,BLACK/BROWN,ROCKY KALAKOS,15220,True,NaN,False
2667,LAB MIX,True,WHITE/BLACK/BROWN,ELLIE,15220,True,NaN,False
2668,GOLDENDOODLE,True,WHITE,CLARENCE,15143,True,NaN,False
2669,SHETLAND SHEEPDOG,True,BLACK,GRIFFIN,15136,True,NaN,False