<a href="https://colab.research.google.com/github/mgodfrey1294/Pandas-Tutorial-Youtube/blob/main/Apply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
# Create Data
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google', 'Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130,120,150]}
# Create DataFrame
my_df = pd.DataFrame(stuff)
my_df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

In [2]:
# Create Function
def times1000(x):
  return format(x * 1000, ',d')

In [3]:
# Use Apply Function
my_df['Salary'].apply(times1000)

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: object

In [4]:
# Make it into a DataFrame
pd.DataFrame(my_df['Salary'].apply(times1000))

    Salary
0  200,000
1  220,000
2  190,000
3  130,000
4  120,000
5  150,000

In [5]:
# Add Elder Last Name
def namer(x):
  if x == "John":
    return "John Elder"
  else:
    return "Not Important"

In [6]:
# Show Elder Last Name
my_df['Employees'].apply(namer)

0       John Elder
1    Not Important
2    Not Important
3    Not Important
4    Not Important
5    Not Important
Name: Employees, dtype: object

In [7]:
# Use Lambda
pd.DataFrame(my_df['Salary'].apply(lambda x: format(x * 1000, ',d')))

    Salary
0  200,000
1  220,000
2  190,000
3  130,000
4  120,000
5  150,000