<a href="https://colab.research.google.com/github/mgodfrey1294/Pandas-Tutorial-Youtube/blob/main/Apply_Multiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
# Create Data
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google', 'Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130,120,150]}
# Create DataFrame
my_df = pd.DataFrame(stuff)
my_df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

In [12]:
# Create Function
def times10(x):
  #return x * 100
  return format(x * 1000, ',d')

In [13]:
my_df['Salary'].apply(times10)

0    200,000
1    220,000
2    190,000
3    130,000
4    120,000
5    150,000
Name: Salary, dtype: object

In [14]:
# Append to current DF
my_df['Salary'] = my_df['Salary'].apply(times10)
my_df

  Corporation Employees   Salary
0       Apple      John  200,000
1      Google     April  220,000
2        Meta       Wes  190,000
3       Apple      Beth  130,000
4      Google    Justin  120,000
5        Meta     Steph  150,000

In [18]:
# Function on multiple columns
def namer(x):
  return "Codemy: " + x

In [19]:
# Apply to Two Columns
my_df[['Corporation', 'Employees']].apply(namer)

      Corporation       Employees
0   Codemy: Apple    Codemy: John
1  Codemy: Google   Codemy: April
2    Codemy: Meta     Codemy: Wes
3   Codemy: Apple    Codemy: Beth
4  Codemy: Google  Codemy: Justin
5    Codemy: Meta   Codemy: Steph

In [20]:
# Append to current DataFrame
my_df[['Corporation', 'Employees']] = my_df[['Corporation', 'Employees']].apply(namer)
my_df

      Corporation       Employees   Salary
0   Codemy: Apple    Codemy: John  200,000
1  Codemy: Google   Codemy: April  220,000
2    Codemy: Meta     Codemy: Wes  190,000
3   Codemy: Apple    Codemy: Beth  130,000
4  Codemy: Google  Codemy: Justin  120,000
5    Codemy: Meta   Codemy: Steph  150,000