<a href="https://colab.research.google.com/github/mgodfrey1294/Pandas-Tutorial-Youtube/blob/main/Sort_Order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
# Create Data
stuff = {
    'Corporation':['Apple', 'Google', 'Meta', 'Apple', 'Google', 'Meta'],
    'Employees':['John', 'April', 'Wes', 'Beth', 'Justin', 'Steph'],
    'Salary':[200, 220, 190, 130,120,150]}
# Create DataFrame
my_df = pd.DataFrame(stuff)
my_df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

In [5]:
# Sort Salaries from lowest to highest
my_df.sort_values('Salary')

  Corporation Employees  Salary
4      Google    Justin     120
3       Apple      Beth     130
5        Meta     Steph     150
2        Meta       Wes     190
0       Apple      John     200
1      Google     April     220

In [6]:
# Sort Salaries from highest to lowest
my_df.sort_values('Salary', ascending=False)

  Corporation Employees  Salary
1      Google     April     220
0       Apple      John     200
2        Meta       Wes     190
5        Meta     Steph     150
3       Apple      Beth     130
4      Google    Justin     120

In [7]:
# Not Permanent without inplace=True
my_df

  Corporation Employees  Salary
0       Apple      John     200
1      Google     April     220
2        Meta       Wes     190
3       Apple      Beth     130
4      Google    Justin     120
5        Meta     Steph     150

In [8]:
# Inplace
#my_df.sort_values('Salary', ascending=False, inplace=True)
my_df.sort_values('Salary', ascending=False, inplace=True)
my_df

  Corporation Employees  Salary
1      Google     April     220
0       Apple      John     200
2        Meta       Wes     190
5        Meta     Steph     150
3       Apple      Beth     130
4      Google    Justin     120

In [9]:
# Sort Strings Alphabetically
my_df.sort_values('Corporation')

  Corporation Employees  Salary
0       Apple      John     200
3       Apple      Beth     130
1      Google     April     220
4      Google    Justin     120
2        Meta       Wes     190
5        Meta     Steph     150

In [10]:
# Sort Strings Alphabetically Descending
my_df.sort_values('Corporation', ascending=False)

  Corporation Employees  Salary
2        Meta       Wes     190
5        Meta     Steph     150
1      Google     April     220
4      Google    Justin     120
0       Apple      John     200
3       Apple      Beth     130